name: deploy_s3

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        run: npm install && npm run-script build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync build/ s3://aegisinitiative-organization-website --acl public-read --delete
      - name: Invalidate Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id $aws-cloudfront-distribution-id --paths "/*"
        env:
          aws-cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} 
